### ISSUE TITLE
能否给PDF加上目录索引？

### ISSUE THREAD

**Issue by iyee** [qyuhen/book#22]
方便阅读时跳转查阅。。

**Comment by monkeycraps** [comment]
好像 pdf 只支持标签吧，没有目录概念的

**Comment by iyee** [comment]
@monkeycraps http://help.adobe.com/zh_CN/acrobat/using/WS58a04a822e3e50102bd615109794195ff-7c37.w.html

**Comment by qyuhen** [comment]
iwork pages 导出 pdf 没有目录项。下一个版本，会改用 online markdown 方式。
