### ISSUE TITLE
第21页中用到的pycat是什么工具?

### ISSUE THREAD

**Issue by huguangju** [qyuhen/book#26]
```python
>> pycat test.py
-bash: pycat: command not found
```

> 网上没有找到

**Comment by shellexy** [comment]
https://github.com/adamcik/pycat

**Comment by huguangju** [comment]
你确定吗，怎么觉得不像
> Main features of pyCAT are:
1) Listen on a given port and relay messages to an IRC channel.
2) Send messages in channel to an external script for parsing, passing output back to channel.

**Comment by shellexy** [comment]
哦抱歉

**Comment by mjlisp** [comment]
IPython里的magic命令。

In [34]: lsmagic
Out[34]:
Available line magics:
%alias  %alias_magic  %autocall  %autoindent  %automagic  %bookmark  %cd  %cls  %colors  %config  %copy  %cpaste  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit
  %env  %gui  %hist  %history  %install_default_config  %install_ext  %install_profiles  %killbgscripts  %ldir  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate
  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %notebook  %page  %paste
  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%latex  %%perl  %%powershell  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Automagic is ON, % prefix IS NOT needed for line magics.

**Comment by huguangju** [comment]
是这个吧[https://github.com/ipython/ipython](https://github.com/ipython/ipython)，好东西
thx
