### ISSUE TITLE
能够给书籍添加一个标签？

### ISSUE THREAD

**Issue by aegsea** [qyuhen/book#31]
你好，你这边的python和golang的书我都挺喜欢，请问能否把书籍导出为pdf时加入一个标签？

**Comment by iyee** [comment]
https://github.com/qyuhen/book/issues/22

**Comment by Liam413** [comment]
yes

**Comment by maxid** [comment]
刚人肉给第4版加了标签
http://pan.baidu.com/s/1i3CcuDR

**Comment by Wooleners** [comment]
> **Note:**
