### ISSUE TITLE
很感谢你写的Go学习笔记

### ISSUE THREAD

**Issue by sunchuo** [qyuhen/book#35]
hi，

很感谢你写的Go学习笔记。建议建一个repository，把md版本按章节提交上来。

像我一样的『初学者』 fork 后可以一边看一边把不全面的地方修改完善。
然后再提交和并请求回来。可以让这本书更好。

再次感谢。

**Comment by Alexsz07** [comment]
Go学习笔记？    什么意思

**Comment by sunchuo** [comment]
你发的pdf不可编辑。看的时候觉得有些地方可以补充一些内容和实例。
提issues没有发 pull request 方便额。

**Comment by dinever** [comment]
同意，不过这样的工程可能太大了。
