### ISSUE TITLE
Go语言笔记有计划写1.5版的么？

### ISSUE THREAD

**Issue by iazkaban** [qyuhen/book#38]
如题

**Comment by sygool** [comment]
算我一个

**Comment by qiyuey** [comment]
+1

**Comment by qyuhen** [comment]
已经在写了。因为年中一些事情耽误，才延迟到今天。不过 1.5 语言部分变化很小，而源码这块除了 GC 引入并发 mark 和写屏障外，其他的可以看做是原 C 的直译。就个人而言，可能还不如 C 版本阅读来得直接，毕竟 1.5 runtime 用 Go 后，一些代码就会一来 Go 1.4 的运行方式，比如初始化规则等等。这些就不如看 C 那么直接了。新版将语言和运行时源码剖析分成两本写。

**Comment by qyuhen** [comment]
另外，Python 新版草稿 6 月份就完成了。但因为 3.5 的发布，在粗略看过源码后，决定升级到 3.5。2.7 虽然使用还很广泛，但从当前语言的发展趋势上来说，已经有些落后了。3.5 的很多特征很值得关注。

**Comment by qyuhen** [comment]
因为年底事情较多，所以时间上不好保证。也可能将 Go 推迟到 1.6 版再发布，得看具体情况了。

**Comment by c9n** [comment]
Python 新稿大概什么时候上？
