### ISSUE TITLE
多级指针也可以直接操作结构字段

### ISSUE THREAD

**Issue by xyoun** [qyuhen/book#51]
Go 学习笔记 120页 第五版第五章数据章节的结构体部分：
“可使用指针直接操作结构字段，但不能是多级指针”
![wechatimg8](https://cloud.githubusercontent.com/assets/3148266/26034962/a522900c-38f7-11e7-992f-a4363e55e2a9.jpeg)

是可以的，需要把 *p2 包起来： `(*p2).name = "Jack"`。

**Comment by xyoun** [comment]
不过按照你的意思，应该是想表达：p2.name = "Jack" 会报错， 而不是 *p2.name = "Jack"。

**Comment by qyuhen** [comment]
那就不是通过指针访问字段了。

(*p2) 已经不是指针了。

**Comment by qyuhen** [comment]
描述的确有问题。
会在下个版本修正。


谢谢！

**Comment by wizardforcel** [comment]
`p`是`*user`，`p2`又做了一次引用应该是`**user`，所以`*p2`是一阶指针，用它是没问题的。但是要包起来。
